### ISSUE TITLE
TLS on mojohaus.org

### ISSUE THREAD

**Issue by vanderaj** [mojohaus/mojohaus.github.io#23]
Hi there,

I look after the @OWASP Top 10, and we want to link to Versions in our standard (it's currently in A9:2017 Known Vulnerabilities). As part of OWASP's commitment to securing the Internet, there will not be any unencrypted links in the OWASP Top 10 going forward. 

Unfortunately, your TLS configuration is not functional for this link: 

https://www.mojohaus.org/versions-maven-plugin/

Your current TLS configuration status:
https://www.ssllabs.com/ssltest/analyze.html?d=www.mojohaus.org&hideResults=on&latest

The OWASP Top 10 has until November 13 to fix any broken links. Do you think you could have a go at fixing the TLS certificate on your site? This will also help with folks using your plugin trust the data it receives from your tool as well. 

I'd strongly suggest your site is only reachable by encrypted means (certbot does this) for all your domains, because version dependency checks are critical to the safety of the Internet at large. If someone can inject a URL for a trojaned dependency in a response from your servers, attackers can run arbitrary code on victim servers. It's critical that projects such as yourselves, Maven, and so on are only reachable via TLS.

**Comment by vanderaj** [comment]
This is the ticket tracking our progress. There's only one other link left and Portswigger are moving their blog to an encrypted link before our go live date. 

https://github.com/OWASP/Top10/issues/183

**Comment by hboutemy** [comment]
Hi Andrew,

thanks for the issue: do you know where we can get a free certificate matching our domain? MojoHaus is an organization without any funds... I'll try to reach other people.

On the severity of not using TLS: this site is absolute pure documentation. Software distribution does not get through this site. I know using TLS is something generally good (and we didn't send people to https since our config is not sufficient).
Are there general ways for us to make that fact clear? Some metatada, or something alike. Something easier than funding certificates (if funding certificates is hard to do given our organization)

thanks

Hervé

**Comment by stefanbirkner** [comment]
`www.mojohaus.org` is a custom domain [hosted on GitHub pages](https://help.github.com/articles/using-a-custom-domain-with-github-pages/). It is easy to get a certificate from e.g. [Let’s Encrypt](https://letsencrypt.org/) but AFAIK GitHub pages doesn't support HTTPS for custom domains. See https://github.com/isaacs/github/issues/156

**Comment by olamy** [comment]
looks fixed by now?
